default_context:
  project_name: 'sports-timeout'
  project_slug: 'sports-timeout'
  domain_main: 'sports-timeout.com'
  domain_staging: 'stag.sports-timeout.com'
  docker_swarm_stack_name_main: 'sports-timeout-com'
  docker_swarm_stack_name_staging: 'stag-sports-timeout-com'
  secret_key: '018Nis.018'
  first_superuser: 'admin@sports-timeout.com'
  first_superuser_password: '018Nis.018'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.sports-timeout.com", "https://stag.sports-timeout.com", "https://sports-timeout.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@sports-timeout.com'
  postgres_password: '018Nis.018'
  pgadmin_default_user: 'admin@sports-timeout.com'
  pgadmin_default_user_password: '018Nis.018'
  traefik_constraint_tag: 'sports-timeout.com'
  traefik_constraint_tag_staging: 'stag.sports-timeout.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:018Nis.018'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
